### PR TITLE
replace carriage return (DOS endings) with newlines; fix broken lines…

### PR DESCRIPTION
**Pull request by jhpoelen**
Hi!
When checking GloBI logs, I noticed some issues in your interactions.tsv, namely:

1. some lines were broken by inserted newlines
2. msdos endings rather than unix endings were used. 
3. unnecessary quotes where used to escape references: tsv don't need quotes. All tsv requires is to not use tabs in any of the fields. See https://en.wikipedia.org/wiki/Tab-separated_values .

I've proposed changed in this pull request. Curious to hear your thoughts.

### CODE REVIEW

**Comment by jhpoelen** [comment]
@fgabriel1891 could you please merge this pull request? These fixes will make your interactions.tsv data better.

**Comment by jhpoelen** [comment]
Let me know if you have any questions about all this.

**Comment by fgabriel1891** [comment]
Hi @jhpoelen. Sorry I have missed this!  Thanks for the pull request. It is all ok now. I will take this into account and check before I upload more data to GloBI next time. Thanks again!

**Comment by fgabriel1891** [comment]
I got this now from the build in TRAVIS: 

 > local	2674 interaction(s)
local	0 error(s)
local	45 warning(s)
java.lang.RuntimeException: org.eol.globi.data.StudyImporterException: check not successful, please check log.
	at org.globalbioticinteractions.elton.cmd.CmdCheck.run(CmdCheck.java:46)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:18)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:27)
	at org.globalbioticinteractions.elton.Elton.main(Elton.java:20)
Caused by: org.eol.globi.data.StudyImporterException: check not successful, please check log.
	at org.globalbioticinteractions.elton.cmd.CmdCheck.check(CmdCheck.java:95)
	at org.globalbioticinteractions.elton.cmd.CmdCheck.checkLocal(CmdCheck.java:70)
	at org.globalbioticinteractions.elton.cmd.CmdCheck.run(CmdCheck.java:41)
	... 3 more
The command "./check-dataset.sh ${TRAVIS_REPO_SLUG}" exited with 1.

**Comment by jhpoelen** [comment]
@fgabriel1891 it looks like some of the rows got misaligned. In reading the (cryptic, sorry!) message:

```
[{referenceCitation=F. Gabriel. Muñoz. 2017. Palm-Animal frugivore associations extracted from literature with Biodiversity Observations Miner for SouthEast Asia.. Accessed at <file:///home/travis/build/fgabriel1891/Plant-Frugivore-Interactions-SouthEastAsia/> on 19 Sep 2018., resourceLineNumber=775, resourceURI=file:///home/travis/build/fgabriel1891/Plant-Frugivore-Interactions-SouthEastAsia/interactions.tsv, sourceTaxonId=89(3), 489-508. DOI: 10.1111/j.1095-8312.2006.00688.x, studySourceCitation=F. Gabriel. Muñoz. 2017. Palm-Animal frugivore associations extracted from literature with Biodiversity Observations Miner for SouthEast Asia.. Accessed at <file:///home/travis/build/fgabriel1891/Plant-Frugivore-Interactions-SouthEastAsia/> on 19 Sep 2018., studyTitle=localF. Gabriel. Muñoz. 2017. Palm-Animal frugivore associations extracted from literature with Biodiversity Observations Miner for SouthEast Asia.. Accessed at <file:///home/travis/build/fgabriel1891/Plant-Frugivore-Interactions-SouthEastAsia/> on 19 Sep 2018.}]
```
I found that the value of the sourceTaxonId is "89(3), 489-508. DOI: 10.1111/j.1095-8312.2006.00688.x", while the targetTaxonName/Id are empty.

**Comment by jhpoelen** [comment]
In this case, the offending line is resourceLineNumber=775 .

**Comment by jhpoelen** [comment]
I've opened some issue #5 #6 with specific pointers. Once these issues are fixed, travis should become a little happier. Thanks for being patient in fixing these data formatting issues.

**Pull request merged**
